name = "KernelIntrinsics"  
uuid = "f9588fbb-d238-4998-b15a-468e8766d49a" 
authors = ["Emmanuel Pilliat <epilliat@gmail.com>"]
version = "0.1.1"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
KernelIntrinsicsCUDAExt = "CUDA"

[compat]
CUDA = "5"
InteractiveUtils = "1.11.0"
KernelAbstractions = "0.9.38"
LLVM = "9"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[targets]
test = ["CUDA", "Test"]